### ISSUE TITLE
.htaccess leading into Error 500

### ISSUE THREAD

**Issue by Svobi** [BaunCMS/Baun#11]
On my LAMP the distributed .htaccess and the documentated on http://bauncms.com/docs/setup/configuration didnt work. 
My Solution
```.htaccess
Options +FollowSymLinks
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /

    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
</IfModule>
```
Well known pattern :-)

**Comment by gilbitron** [comment]
Ok good to know. We can't cover every possible server config, but this might be helpful for someone else.
