### ISSUE TITLE
Kill Pico?

### ISSUE THREAD

**Issue by n1trux** [BaunCMS/Baun#13]
Hey,

Since [Pico](https://github.com/picocms/Pico) development has pretty much stalled, why don't you put a notice on the website/repo that Baun is "the new shit"?

**Comment by williamgb** [comment]
As far as I know PicoCMS is no longer lead by @gilbitron. I'd like to recommend filing a PR at https://github.com/picocms but sadly the project seems to have been abandoned.

**Comment by gilbitron** [comment]
Pico doesn't belong to me anymore, so I don't want to create a big fuss about Pico being Bauns predecessor.
