### ISSUE TITLE
Sort order of pages in menu

### ISSUE THREAD

**Issue by GrimLink** [BaunCMS/Baun#20]
Unable to sort a pages after a folder in the menu.
Folders are always ordered after the pages.
![screen shot 2016-07-12 at 20 26 37](https://cloud.githubusercontent.com/assets/4387541/16779054/f734388c-4870-11e6-8b83-efdbb093fb2c.png)
![screen shot 2016-07-12 at 20 36 20](https://cloud.githubusercontent.com/assets/4387541/16779053/f731705c-4870-11e6-8bb0-103683b7f5c0.png)

**Comment by 00091701** [comment]
Did you find a solution?
I have the same problem on my website.

**Comment by GrimLink** [comment]
@00091701 I haven't tried to solve this.
Best case is an combination of the Baun menu and some static menu items.
Not perfect but it works 😕

**Comment by GrimLink** [comment]
I am closing this issue since Baun is not maintained anymore.
