### ISSUE TITLE
plugins not work ...

### ISSUE THREAD

**Issue by thefree** [BaunCMS/Baun#9]
Can't use method return value in write context in /var/www/Baun/vendor/bauncms/framework/src/Baun.php on line 58

**Comment by michherren** [comment]
To resolve this issue, set your php-version to 5.5 or higher. There are some php-features used, which are only available from php 5.5+  (empty() with arbitrary expressions).

**Comment by thefree** [comment]
all unix distribution use php 5.4+ , mb correctly, make work on 5.3/5.4

**Comment by michherren** [comment]
Had the same issue on a server. Fixed it in a fork and created a pull-request to the braun-framework:
https://github.com/BaunCMS/Framework/pull/2

**Comment by gilbitron** [comment]
Thanks. I've pushed this fix in Framework v1.2.2.
